services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'secretdb'
      POSTGRES_USER: 'userdb'
      POSTGRES_DB: 'sampledb'

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/src
      - /src/node_modules
    ports:
      - "5173:5173"
